### ISSUE TITLE
Integration tests are broken

### ISSUE THREAD

**Issue by deusebio** [canonical/kafka-test-app#17]
The integration tests in the CI are not working correctly, see [here](https://github.com/canonical/kafka-test-app/actions/runs/8277657507/job/22648424487)

**Comment by Batalex** [comment]
In https://github.com/canonical/kafka-test-app/blob/main/.github/workflows/ci.yaml#L54-L57, the juju channel should be set as follows

```yaml
with:
  juju-channel: 3/stable
```

**Comment by deusebio** [comment]
Oh, yes. Let's give it a shot. If it does not work (meaning that maybe we need the fix requires substantially more effort) we can then address it structurally. In the latter case, we can just provide some extra info to help us size the effort and prioritize this ticket

**Comment by Batalex** [comment]
The fix *could* be straightforward, as in, "we could set juju version to 2.X", but wouldn't it be the opportunity to upgrade the deps?
Using "3.1/stable" fails because `ops`  2.5 is incompatible
